version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:16.20
    working_directory: ~/project

jobs:
  test:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install Node Dependencies
          command: npm install playwright@latest --save-dev

      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps

      - run:
          name: Run Playwright Tests with Allure
          command: |
            npx playwright test --reporter=line,allure-playwright
            mkdir -p allure-report && npx allure generate allure-results --clean -o allure-report

      - store_artifacts:
          path: allure-report
          destination: allure-report

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
