version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16  # Use Node.js 16 Docker image
    working_directory: ~/project

jobs:
  test:
    executor: node-executor

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Install Playwright Browsers
          command: npx playwright install

      - run:
          name: Run Playwright Tests with Allure
          command: |
            npx playwright test --reporter=line,allure-playwright
            mkdir -p allure-report && npx allure generate allure-results --clean -o allure-report

      - store_artifacts:
          path: allure-report  # Save Allure report as CircleCI artifact
          destination: allure-report

      - run:
          name: Send Slack Notification
          command: |
            if [ $? -eq 0 ]; then
              STATUS_MESSAGE="Build and Tests Passed! 🎉"
              COLOR="good"
            else
              STATUS_MESSAGE="Build or Tests Failed! ❌"
              COLOR="danger"
            fi
            
            curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"attachments\": [
                {
                  \"fallback\": \"CircleCI Build Notification\",
                  \"color\": \"$COLOR\",
                  \"text\": \"$STATUS_MESSAGE\",
                  \"fields\": [
                    { \"title\": \"Project\", \"value\": \"$CIRCLE_PROJECT_REPONAME\", \"short\": true },
                    { \"title\": \"Branch\", \"value\": \"$CIRCLE_BRANCH\", \"short\": true },
                    { \"title\": \"Build URL\", \"value\": \"$CIRCLE_BUILD_URL\", \"short\": false },
                    { \"title\": \"Allure Report\", \"value\": \"https://<your-username>.github.io/<repository-name>/\", \"short\": false }
                  ]
                }
              ]
            }" $SLACK_WEBHOOK_URL
        environment:
          SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL  # Ensure the webhook URL is added as an environment variable in CircleCI

  deploy-allure-report:
    executor: node-executor

    steps:
      - checkout

      - run:
          name: Install Git
          command: sudo apt-get install git -y

      - run:
          name: Download Allure Report
          command: |
            git clone https://github.com/oletishiva/playwright-allure-e2e.git report-branch
            cd report-branch && mkdir -p allure-report
            cp -r ~/project/allure-report/* ./allure-report

      - run:
          name: Deploy Allure Report to GitHub Pages
          command: |
            cd report-branch
            git config --global user.name "oletishiva"
            git config --global user.email "oletishiva@gmail.com"
            git add .
            git commit -m "Update Allure Report"
            git push origin report-branch

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy-allure-report:
          requires:
            - test
