version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16
    working_directory: ~/project

jobs:
  test:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Update Repositories
          command: |
            sudo sed -i 's/deb.debian.org\/debian/deb.debian.org\/debian-archive/g' /etc/apt/sources.list
            sudo apt-get update

      - run:
          name: Install Playwright Dependencies
          command: sudo npx playwright install-deps

      - run:
          name: Install Node Dependencies
          command: npm install

      - run:
          name: Install Playwright Browsers
          command: npx playwright install

      - run:
          name: Run Playwright Tests with Allure
          command: |
            npx playwright test --reporter=line,allure-playwright
            mkdir -p allure-report && npx allure generate allure-results --clean -o allure-report

      - store_artifacts:
          path: allure-report
          destination: allure-report

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
