version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16
    working_directory: ~/project

jobs:
  test:
    executor: node-executor

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Install Playwright Browsers
          command: npx playwright install

      - run:
          name: Run Playwright Tests with Allure
          command: |
            npx playwright test --reporter=line,allure-playwright
            mkdir -p allure-report && npx allure generate allure-results --clean -o allure-report

      - store_artifacts:
          path: allure-report
          destination: allure-report

      - run:
          name: Send Slack Notification
          command: |
            echo "Sending Slack Notification..." 

workflows:
  version: 2
  test-workflow:
    jobs:
      - build-and-test
