version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16
    working_directory: ~/project

jobs:
  test:
    executor: node-executor

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Install Playwright Browsers
          command: npx playwright install

      - run:
          name: Run Playwright Tests with Allure
          command: |
            npx playwright test --reporter=line,allure-playwright
            mkdir -p allure-report && npx allure generate allure-results --clean -o allure-report

      - store_artifacts:
          path: allure-report
          destination: allure-report

      - run:
          name: Send Slack Notification
          command: |
            # Define success or failure based on the previous step
            if [ $? -eq 0 ]; then
              STATUS_MESSAGE="Build and Tests Passed! 🎉"
              COLOR="good"
            else
              STATUS_MESSAGE="Build or Tests Failed! ❌"
              COLOR="danger"
            fi

            # Send the notification
            curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"attachments\": [
                {
                  \"fallback\": \"CircleCI Build Notification\",
                  \"color\": \"$COLOR\",
                  \"text\": \"$STATUS_MESSAGE\",
                  \"fields\": [
                    { \"title\": \"Project\", \"value\": \"$CIRCLE_PROJECT_REPONAME\", \"short\": true },
                    { \"title\": \"Branch\", \"value\": \"$CIRCLE_BRANCH\", \"short\": true },
                    { \"title\": \"Build URL\", \"value\": \"$CIRCLE_BUILD_URL\", \"short\": false },
                    { \"title\": \"Allure Report\", \"value\": \"https://oletishiva.github.io/playwright-allure-e2e/\", \"short\": false }
                  ]
                }
              ]
            }" "$SLACK_WEBHOOK_URL"
        environment:
          SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
