name: Playwright Tests with Allure Reports

on:
  #push:
    #branches:
      #- main
  #pull_request:
    #branches:
      #- main
  workflow_dispatch: # Keep this to allow manual triggering of the workflow
  pull_request:      # (Optional) Trigger only on pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install  #

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --silent

      - name: Run Playwright tests with Allure
        run: |
          npx playwright test --reporter=line,allure-playwright
        continue-on-error: true  # Allow tests to fail without stopping the workflow

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
        if: always()  # Ensure this step runs even if the previous step fails

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
        if: always()  # Ensure this step runs even if the previous step fails

  publish-allure-report:
    needs: test  # Runs after the test job
    runs-on: ubuntu-latest

    permissions:  # Allow write permissions for Pages
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure Report
        uses: actions/download-artifact@v3
        with:
          name: allure-report

      - name: Deploy Allure Report to Report branch # git hub pages have permission issues i think
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: report-branch
          publish_dir: allure-report

  notify:
    needs: test  # Runs after the test job
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Playwright CI/CD Pipeline completed. <${{ github.run_url }}|View Logs>\nView Allure Report: <https://oletishiva.github.io/playwright-allure-e2e/|View Allure Report>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
