name: Playwright Tests with Allure Reports

on:
  workflow_dispatch: # Allow manual triggering of the workflow
  pull_request:      # Trigger on pull requests

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --silent

      - name: Run Playwright tests with Allure
        run: |
          npx playwright test --reporter=line,allure-playwright
        continue-on-error: true  # Allow tests to fail without stopping the workflow

      - name: Merge Playwright Reports
        run: npx playwright merge-reports --reporter allure --outputDir allure-results
        if: always()

      - name: Generate Allure Report
        run: |
          if [ -d "allure-results" ] && [ "$(ls -A allure-results)" ]; then
            allure generate allure-results --clean -o allure-report
          else
            echo "No Allure results found. Skipping report generation."
          fi
        if: always()

      - name: Upload Allure Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  publish-allure-report:
    needs: test  # Runs after the test job
    runs-on: ubuntu-latest

    permissions:  # Allow write permissions for Pages
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure Report
        uses: actions/download-artifact@v4
        with:
          name: allure-report

      - name: Verify Allure Report Before Deploying
        run: |
          if [ -d "allure-report" ] && [ "$(ls -A allure-report)" ]; then
              echo "Allure Report found. Proceeding with deployment."
          else
              echo "No Allure report found. Failing the job."
              exit 1
          fi

      - name: Deploy Allure Report to Report branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN instead of personal_token
          publish_branch: report-branch
          publish_dir: allure-report

  notify:
    needs: test  # Runs after the test job
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Playwright CI/CD Pipeline completed. <${{ github.run_url }}|View Logs>\nView Allure Report: <https://oletishiva.github.io/playwright-allure-e2e/|View Allure Report>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}