name: Playwright Tests with Allure Reports AND Parallel Execution 

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [1, 2, 3]  # Run tests in parallel using 3 containers

    container:
      image: mcr.microsoft.com/playwright:v1.47.2-jammy
      env:
        HOME: /root  # Fix Firefox launch issue

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps  # Installs required browsers

      - name: Install Java (Required for Allure)
        run: apt-get update && apt-get install -y openjdk-11-jdk  # Install Java without sudo

      - name: Install Allure CLI and Playwright Plugin
        run: npm install -g allure-commandline allure-playwright --silent

      - name: Run Playwright tests with Allure
        run: |
          mkdir -p allure-results  # Ensure directory exists
          npx playwright test --reporter=line,allure-playwright --workers=2
        continue-on-error: true  # Allow tests to fail without stopping the workflow

      - name: Debug: Check Allure Results Before Uploading
        run: ls -R allure-results || echo "No Allure results found!"

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.container }}
          path: allure-results
        if: always()

  merge-reports:
    needs: test  # Runs after all test jobs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Allure CLI
        run: npm install -g allure-commandline --silent

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          path: allure-results
          pattern: allure-results-*
          merge-multiple: true

      - name: Debug: Check Downloaded Allure Results Before Merging
        run: ls -R allure-results || echo "No Allure results found!"

      - name: Merge Allure Reports
        run: |
          mkdir -p allure-results  # Ensure directory exists
          npx playwright merge-reports --reporter=html allure-results/

      - name: Upload Merged Report
        uses: actions/upload-artifact@v4
        with:
          name: merged-allure-report
          path: allure-results
        if: always()

  publish-allure-report:
    needs: merge-reports
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Merged Report
        uses: actions/download-artifact@v4
        with:
          name: merged-allure-report
          path: allure-report  # Ensure it is downloaded correctly

      - name: Deploy Allure Report to Report Branch  # GitHub Pages deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: report-branch
          publish_dir: allure-report  # Correct directory for publishing

  notify:
    needs: merge-reports
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Playwright CI/CD Pipeline completed. <${{ github.run_url }}|View Logs>\nView Allure Report: <https://oletishiva.github.io/playwright-allure-e2e/|View Report>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
