name: Playwright Tests with Parallel Execution & Allure Reports

on:
  workflow_dispatch:  # Allows manual triggering
  pull_request:       # Runs on pull request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [1, 2, 3]  # Defines how many parallel containers to use

    container:
      image: mcr.microsoft.com/playwright:v1.47.2-jammy  # Uses Playwright Docker image
      env:
        HOME: /root  # Fix Firefox launch issue

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps  # Installs required browsers

      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      - name: Install Java (Required for Allure)
        run: apt update && sudo apt install -y openjdk-11-jdk

      - name: Install Allure CLI
        run: npm install -g allure-commandline --silent

      - name: Run Playwright tests in Parallel
        run: |
          TEST_FILES=$(ls tests/*.spec.ts | awk "NR % ${{ strategy.job-total }} == $(( ${{ matrix.container }} - 1 ))")
          if [[ -z "$TEST_FILES" ]]; then
            echo "No tests assigned to this container"
            exit 0
          fi
          echo "Running tests: $TEST_FILES"
          npx playwright test $TEST_FILES --reporter=line,allure-playwright --workers=2
        continue-on-error: true  # Allow tests to fail without stopping the workflow

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
        if: always()  # Runs even if previous steps fail

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.container }}
          path: allure-report
        if: always()  # Runs even if tests fail

  merge-reports:
    needs: test  # Runs after all test jobs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Allure CLI
        run: npm install -g allure-commandline --silent

      - name: Download Allure Reports
        uses: actions/download-artifact@v4
        with:
          path: allure-reports
          pattern: allure-report-*
          merge-multiple: true

      - name: Merge Allure Reports
        run: npx playwright merge-reports --reporter=html ./allure-reports

      - name: Upload Final Merged Report
        uses: actions/upload-artifact@v4
        with:
          name: merged-allure-report
          path: allure-reports
        if: always()

  publish-allure-report:
    needs: merge-reports  # Runs after merging reports
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Merged Report
        uses: actions/download-artifact@v4
        with:
          name: merged-allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: report-branch
          publish_dir: merged-allure-report

  notify:
    needs: merge-reports  # Runs after merging reports
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Playwright CI/CD Pipeline completed. <${{ github.run_url }}|View Logs>\nView Allure Report: <https://oletishiva.github.io/playwright-allure-e2e/|View Report>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
